spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usedcar?serverTimezone=UTC
    username: test
    password: 1234

    # <h2 ????? - ????>
  #    url: jdbc:h2:~/test;
  #    username: sa
  #    password:

  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  SECRET_KEY: afassakjdhajskdhlaskhdlkahlksahgkalhrskjghdlkshgjlsdahgjhsjknkfnkdsnfkjndsjkfnsjfndjsnfjkdnf
  EXP_TIME: 3600000
